version: '1.0'
name: pipeline-testcli
displayName: 流水线-TestCli
triggers:
  trigger: manual
  push:
    branches:
      precise:
        - master
  pr:
    branches:
      precise:
        - master
stages:
  - name: stage-pipeline
    displayName: 流水线任务
    strategy: naturally
    trigger: auto
    executor:
      - RobotSlacker
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - python setup.py install
          - python -m testcli.cliconsole --selftest
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '0'
